[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["formidable", "nodemailer"]
  included_files = ["netlify/functions/*.cjs"]

[dev]
  framework = "vite"
  target = "."
  command = "npm run dev"
  port = 5174  # Changement de port pour éviter le conflit avec Vite
  publish = "dist"
  functions = "netlify/functions"
  
  [dev.proxy]
    # Configuration du proxy pour rediriger les requêtes API vers le port de Vite
    "/api/*" = { from = "/api/*", to = "http://localhost:5173/api/:splat" }

# Redirection pour les fonctions Netlify
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirection pour l'API (au cas où)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
